---

dependencies:

  - role: debops.secret
    tags: [ 'depend::secret', 'depend::secret:sshkeys',
            'depend-of::sshkeys', 'type::dependency:hard' ]

galaxy_info:

  author: 'Maciej Delmanowski'
  description: 'Manage system-wide user SSH keys in /etc/ssh/authorized_keys/'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'

  platforms:

  - name: Ubuntu
    versions:
      - precise
      - quantal
      - raring
      - saucy
      - trusty

  - name: Debian
    versions:
      - wheezy
      - jessie

  galaxy_tags:
    - system
    - ssh
    - publickey
    - security


