---

- name: Install openVPN
  apt: name=openvpn state=present

- name: Install resolvconf
  apt: name=resolvconf state=present
  when: openvpn_dns

- name: Extract config and keys
  unarchive: 
    src: "/tmp/openvpn/{{ fqdn }}.tar.gz"
    dest: "{{ openvpn_etcdir }}"
    owner: root
    group: root
    mode: 0600
  notify: [openvpn restart]
