---

- name: Create sys backup file
  template:
    src: 19.sys.j2
    dest: /etc/backup.d/19.sys
    owner: root
    group: root
    mode: 0600
  when: sys_bkup == "yes"

- name: Delete sys backup file if no longer needed
  file:
    path: /etc/backup.d/19.sys
    state: absent
  when: sys_bkup == "no"

- name: Create my.cnf file for root
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  when: my_sql_bkup == "yes"

- name: Delete my.cnf file if no longer needed
  file:
    path: /root/.my.cnf
    state: absent
  when: my_sql_bkup == "no"

- name: Create mysql backup file
  template:
    src: 29.mysql.j2
    dest: /etc/backup.d/29.mysql
    owner: root
    group: root
    mode: 0600
  when: my_sql_bkup == "yes"

- name: Delete mysql backup file if no longer needed
  file:
    path: /etc/backup.d/29.mysql
    state: absent
  when: my_sql_bkup == "no"

- name: Create postgresql backup file
  template:
    src: 39.pgsql.j2
    dest: /etc/backup.d/39.pgsql
    owner: root
    group: root
    mode: 0600
  when: pg_sql_bkup == "yes"

- name: Delete postgresql backup file if no longer needed
  file:
    path: /etc/backup.d/39.pgsql
    state: absent
  when: pg_sql_bkup == "no"

- name: Create duplcity backup file
  template:
    src: 99.dup.j2
    dest: /etc/backup.d/99.dup
    owner: root
    group: root
    mode: 0600
  when: dup_bkup == "yes"

- name: Delete duplicity backup file if no longer needed
  file:
    path: /etc/backup.d/99.dup
    state: absent
  when: dup_bkup == "no"
