---

- name: Configure apt to install duplicity from jessie
  template:
    src: duplicity_jessie.j2
    dest: /etc/apt/preferences.d/duplicity
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'wheezy'

- name: Set jessie source list in apt
  apt_repository: 
    repo: "deb ftp://ftp.gr.debian.org/debian/ jessie main"
    state: present
    filename: 'jessie'
    mode: 0644
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'wheezy'

- name: Set jessie source list in apt
  apt_repository: 
    repo: "deb-src ftp://ftp.gr.debian.org/debian/ jessie main"
    state: present
    filename: 'jessie'
    mode: 0644
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'wheezy'

- name: Install backupninja and update apt's cache
  apt:
    name: backupninja
    state: latest
    update_cache: yes

- name: Install duplicity
  apt:
    name: duplicity
    state: latest
