---

- include: install_packets.yml

- include: gpg.yml

- include: duplicity.yml

- include: ssh.yml

################################################################################
################################################################################
################################################################################

#- name: Test backupninja mysql backup
#  shell: backupninja -d -n --run /etc/backup.d/29.mysql
#  when: my_sql_bkup == "yes"
#
#- name: Test backupninja postgressql backup
#  shell: backupninja -d -n --run /etc/backup.d/39.pgsql
#  when: pg_sql_bkup == "yes"
#
#- name: Test backupninja full backup
#  shell: backupninja -d -n --run /etc/backup.d/99.dup

################################################################################
################################################################################
################################################################################

#- name: Get key fingerpring
#  shell: gpg --list-secret-keys --with-colons --fingerprint  backup |grep fpr |cut -d ':' -f 10
#  register: fpr
#- name: Delete secret gpg key
#  shell: gpg --batch --delete-secret-keys {{ fpr.stdout | quote }}
#- name: Delete public gpg key
#  shell: gpg --batch --delete-keys {{ fpr.stdout | quote }}

#- name: Remove server from known hosts
#  shell: sed -i '/.*pensieve.*/d' /root/.ssh/known_hosts

#- name: Change host
#  shell: sed -i 's/Host pensieve/Host pensieve.ellak.gr/g' /root/.ssh/config

#- name: Check if postgresql is active
##  shell: which pg_dump 2>&1 >/dev/null
#  shell: service postgresql status

#- name: Check if mysql is active
#  shell: service mysql status
