---

- name: Create ssh directory if it isn't there
  file:
    path: "/root/.ssh"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Insert server host to config if it isn't there
  blockinfile:
    dest: /root/.ssh/config
    owner: root
    group: root
    mode: 0600
    block: "{{ backupninja_host_config }}"

- name: Check for ssh-key
  shell: cat /root/.ssh/bkup.pub
  register: result
  ignore_errors: True
  changed_when: false
- debug:
    var : "{{ result.stdout_lines }}"

- name: Create a new ssh-key if there isn't one
  shell: ssh-keygen -t rsa -b 4096 -N "" -C "BackupKey-$(date -I)" -f /root/.ssh/bkup
  when: result|failed 

- name: Print the new ssh-key
  shell: cat /root/.ssh/bkup.pub
  when: result|failed 

- name: Insert server host-key if it isn't already there
  known_hosts: 
    path: '/root/.ssh/known_hosts'
    name: "{{ item.name }}"
    key: "{{ item.key }}"
    state: present
  with_items: "{{ backupninja_host_key }}"
