---
# handlers file for mariadb
- name: restart mariadb
  service: name=mariadb state=restarted
  when: ansible_os_family == 'RedHat'

- name: restart mariadb
  service: name=mysql state=restarted
  when: ansible_os_family == 'Debian'
