---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-sftpusers"
  git_branch: "master"
  galaxy_id: "1599"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    `debops.sftpusers` role can be used to create and manage user accounts
    which have system access restricted to SFTP only.
    
    Access to SFTPonly accounts is allowed only using SSH public keys, but
    users cannot manage their own keys. Instead, sshd server uses keys from
    `/etc/ssh/authorized_keys/<user>` for authorization. Use
    `debops.sshkeys` role to manage these keys separately.

