---
# tasks file for roles/hhvm
- name: Get HHVM repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '0x5a16e7281be7a449'

- name: Install HHVM repo
  apt_repository:
    repo: "deb http://dl.hhvm.com/debian {{ ansible_lsb.codename }} main"
    state: present
    update_cache: yes

- name: Install HHVM
  apt:
    name: hhvm
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Copy /etc/hhvm/server.ini
  template:
    src: etc/hhvm/server.ini.j2
    dest: /etc/hhvm/server.ini
    owner: root
    group: root
    mode: 0644
  notify: hhvm restart

- name: Copy /etc/hhvm/php.ini
  template:
    src: etc/hhvm/php.ini.j2
    dest: /etc/hhvm/php.ini
    owner: root
    group: root
    mode: 0644
  notify: hhvm restart

- name: Ensure HHVM is running
  service: name=hhvm state=started enabled=yes
