---
# --- Paths ---

monit_lib: '/var/lib/monit'
monit_run_state: '/var/run/monit'
monit_events: '{{ monit_lib }}/events'
monit_base_process_run_state: '/var/run'

# --- Globals ---

monit_logfile: syslog
monit_idfile: '{{ monit_lib }}/id'
monit_statefile: '/var/lib/monit/state'

