---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Configure MariaDB
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mariadb

- name: Ensure MariaDB is started and enabled on boot
  service: name=mariadb state=started enabled=yes

- include: secure-installation.yml

- include: databases.yml

- include: users.yml
