---
# Mediawiki extensions

composer_extensions:
  - name: 'mediawiki/validator'
    version: '2.0.*'
  - name: 'mediawiki/semantic-media-wiki'
    version: '~2.2'
  - name: 'mediawiki/maps'
    version: '*'
  - name: 'mediawiki/semantic-maps'
    version: '*'
  - name: 'mediawiki/semantic-extra-special-properties'
    version: '~1.3'

# Place here any extension that is in Wikimedia's repository
# https://git.wikimedia.org/summary/?r=mediawiki/extensions.git
wikimedia_git_extensions:
  - name: 'LocalisationUpdate'
    description: 'allows to update the localizations for MediaWiki messages at any time, without needing to upgrade the MediaWiki software.'
    load_syntax: 'new'
    options: '$wgLocalisationUpdateDirectory = "$IP/cache";'
  - name: 'BetaFeatures'
    description: 'test new features on Wikipedia and other Wikimedia sites before they are released for everyone.'
    load_syntax: 'new'
  - name: 'CommonsMetadata'
    description: 'extract metadata from Wikimedia Commons pages.'
    load_syntax: 'new'
  - name: 'ParserFunctions'
    description: 'enhances the wikitext parser with helpful functions.'
    load_syntax: 'new'
    options: '$wgPFEnableStringFunctions = false;'
  - name: 'TemplateData'
    description: 'introduces a <templatedata> tag and an API which together allow editors to specify how templates should be invoked.'
    load_syntax: 'new'
    options: '$wgTemplateDataUseGUI = false;'
  - name: 'Gadgets'
    description: 'provides a way for users to pick JavaScript or CSS based "gadgets" that other wiki users provide.'
    load_syntax: 'new'
  - name: 'Cite'
    description: 'allows a user to create references as footnotes on a page.'
    load_syntax: 'new'
  - name: 'MultimediaViewer'
    description: 'different interface for viewing full-size, or nearly full-size, images.'
    load_syntax: 'old'
  - name: 'Scribunto'
    description: 'allows for embedding scripting languages in MediaWiki. Currently the only supported scripting language is Lua.'
    load_syntax: 'old'
    options: "$wgScribuntoDefaultEngine = 'luastandalone';"
  - name: 'SandboxLink'
    description: "adds a link to user's personal sandbox to personal tools menu."
    load_syntax: 'old'
  - name: 'Maps'
    description: 'visualize geographic data with dynamic, JavaScript-based mapping APIs such as Google Maps, OpenStreetMap, and OpenLayers in your wiki pages.'
    load_syntax: 'old'
  - name: 'AdminLinks'
    description: 'defines a special page, "Special:AdminLinks", that holds links meant to be helpful for wiki administrators.'
    load_syntax: 'old'
  - name: 'ExternalData'
    description: ' allows MediaWiki pages to retrieve, filter, and format structured data from one or more sources.'
    load_syntax: 'old'
  - name: 'HeaderTabs'
    description: 'transforms top-level MediaWiki headers into tabs using the jQuery UI JavaScript library.'
    load_syntax: 'old'
  - name: 'PageSchemas'
    description: 'allows for defining all the schema information about a "class", or data type - for naming, display, data input, and browsing - within a single piece of XML contained within a category page.'
    load_syntax: 'old'
  - name: 'ReplaceText'
    description: 'provides a special page, as well as a command-line script, to allow administrators to do a global string find-and-replace on both the text and titles of the wiki  content pages.'
    load_syntax: 'old'
  - name: 'Widgets'
    description: 'allows the creation of raw HTML pages that can be embedded (similarly to templates) in normal wiki pages.'
    load_syntax: 'old'
    options: "$wgGroupPermissions['sysop']['editwidgets'] = true;   // do some permission setup"
  - name: 'VisualEditor'
    description: 'aims to create a reliable rich-text editor for the Web and for MediaWiki.'
    load_syntax: 'old'
    options: |
      $wgDefaultUserOptions['visualeditor-enable'] = 1; // allow for everybody
      $wgHiddenPrefs[] = 'visualeditor-enable';         // do not allow users to disable it
      ## URL to the Parsoid instance MUST NOT end in a slash due to Parsoid bug
      $wgVisualEditorParsoidURL = 'http://{{ parsoid_ip }}:8000';
      $wgVisualEditorParsoidPrefix = '{{ parsoid_api_endpoints[0].uid }}';
      ## Parsoid breaks with https
      ## http://www.mediawiki.org/wiki/Talk:Parsoid#Run_parsoid_over_https.3F
      $wgSessionsInObjectCache = true;
  - name: 'SemanticForms'
    description: 'an extension to MediaWiki that allows users to add, edit and query data using forms.'
    load_syntax: 'old'
  - name: 'SemanticFormsInputs'
    description: 'provides additional input types for Semantic MediaWikis that use the Semantic Forms extension.'
    load_syntax: 'old'
  - name: 'SemanticDrilldown'
    description: "provides a page for drilling down through a site's data, using categories and filters on semantic properties."
    load_syntax: 'old'
  - name: 'SemanticImageInput'
    description: 'allows for automatic adding of images from Wikipedia pages via a Semantic Forms input.'
    load_syntax: 'old'
  - name: 'SemanticTasks'
    description: 'provides email task notifications and reminders.'
    load_syntax: 'old'
  - name: 'CiteThisPage'
    load_syntax: 'new'
  - name: 'ImageMap'
    load_syntax: 'new'
  - name: 'InputBox'
    load_syntax: 'new'
  - name: 'Interwiki'
    load_syntax: 'new'
  - name: 'Nuke'
    load_syntax: 'new'
  - name: 'PdfHandler'
    load_syntax: 'new'
  - name: 'Renameuser'
    load_syntax: 'new'
  - name: 'SpamBlacklist'
    load_syntax: 'new'
  - name: 'SyntaxHighlight_GeSHi'
    load_syntax: 'new'
  - name: 'TitleBlacklist'
    load_syntax: 'new'
  - name: 'WikiEditor'
    load_syntax: 'new'

# Extensions from other git repositories, ie. GitLab, GitHub, BitBucket
# extra_git_extensions:
#   name:
#   description:
#   load_syntax:
#   options:
#   comments:
#   dir:
extra_git_extensions: []
