---

month: "Ιανουάριος 2016"
title: "ΕΛΛΑΚ ΝΕΑ - {{ month }}"

ellak:
- { desc: "FOSDEM 2016: Η Ευρωπαϊκή γιορτή του ελεύθερου λογισμικού στις 30-31 Ιανουαρίου",
    url: "https://ellak.gr/2016/01/fosdem-2016-evropaiki-giorti-tou-eleftherou-logismikou-stis-30-31-ianouariou/" }
- { desc: "Πρόσκληση για διαβούλευση στη διαμόρφωση τριών μελετών-οδηγών για τη χρήση, διάθεση και προώθηση του ΕΛ/ΛΑΚ",
    url: "https://ellak.gr/2016/01/prosklisi-gia-diavoulefsi-sti-diamorfosi-trion-meleton-odigon-gia-ti-chrisi-diathesi-ke-proothisi-tou-ellak/" }
- { desc: "Οι δράσεις και η ομάδα του ODI Αthens",
    url: "https://ellak.gr/2016/01/drasis-ke-omada-tou-odi-athens/" }

cc:
- { desc: "Ο σκοταδισμός της πνευματικής ιδιοκτησίας – #opensource #digitalrights #greek",
    url: "https://creativecommons.ellak.gr/2016/01/18/o-skotadismos-tis-pnevmatikis-idioktisias-opensource-digitalrights-greek/" }
- { desc: "NYPL: Πάνω απο 180.000 ψηφιακά έργα με άδεια κοινού κτήματος απο την Βιβλιοθήκη της Νέας Υόρκης",
    url: "https://creativecommons.ellak.gr/2016/01/08/nypl-pano-apo-180-000-psifiaka-erga-me-adia-kinou-ktimatos-apo-tin-vivliothiki-tis-neas-iorkis/" }

mycontent:
- { desc: "Τέχνη των Κοινών: η ελληνική ανοικτή λογοτεχνική σκηνή",
    url: "https://mycontent.ellak.gr/2016/01/28/techni-ton-kinon-i-elliniki-anikti-logotechniki-skini/" }
- { desc: "Νικητές του ελληνικού μέρους του Διαγωνισμού Επιστημονικής Φωτογραφίας Wikimedia 2015",
    url: "https://mycontent.ellak.gr/2016/01/27/nikites-tou-ellinikou-merous-tou-diagonismou-epistimonikis-fotografias-wikimedia-2015/" }
- { desc: "Κάλεσμα συμμετοχής στα ελεύθερα μαθήματα Βικιπαίδειας στο 8ο Γυμνάσιο Αθηνών”",
    url: "https://mycontent.ellak.gr/2016/01/11/kalesma-simmetochis-sta-elefthera-mathimata-vikipedias-sto-8o-gimnasio-athinon/" }
- { desc: "Μαθησιακή Ηλεκτρονική Τράπεζα Ιδιαίτερης αξίας Διδακτικών Αντικειμένων – #gredu",
    url: "https://mycontent.ellak.gr/2016/01/08/mathisiaki-ilektroniki-trapeza-idieteris-axias-didaktikon-antikimenon-gredu/" }
- { desc: "Κατεβάστε 45.000 πίνακες ζωγραφικής από την National #Gallery of #Art – #openaccess",
    url: "https://mycontent.ellak.gr/2016/01/03/katevaste-45-000-pinakes-zografikis-apo-tin-national-gallery-of-art-openaccess/" }

planet:
- { desc: "Ανασκόπηση #2015 των δράσεων της κοινότητας #ownCloud",
    url: "https://ellak.gr/2016/01/planet-ellak-gr-anaskopisi-2015-ton-draseon-tis-kinotitas-owncloud/" }
- { desc: "Ανασκόπηση #2015 της κοινότητας #bitcoin-gr",
    url: "https://ellak.gr/2016/01/planet-ellak-gr-anaskopisi-2015-tis-kinotitas-bitcoin-gr/" }
- { desc: "Οδηγίες προς ναυτιλομένους: Πρώτες κινήσεις μετάβασης από Windows σε Linux",
    url: "https://ellak.gr/2016/01/nea-apo-ton-planiti-planet-ellak-grodigies-pros-naftilomenous-protes-kinisis-metavasis-apo-windows-se-linux/" }
- { desc: " Drupal Day 2016",
    url: "https://ellak.gr/2016/01/nea-apo-ton-planitiplanet-ellak-gr-drupal-day-2016/" }
- { desc: "Δεκαπέντε χρόνια πριν η Βικιπαίδεια ήταν ένας εντελώς διαφορετικός τόπος",
    url: "https://ellak.gr/2016/01/nea-apo-ton-planitiplanet-ellak-gr-dekapente-chronia-prin-vikipedia-itan-enas-entelos-diaforetikos-topos/" }

opengov: []

opendata: []

odi: []

obs: []

edu: 
- { desc: "Σχολικό Εργαστήριο Ανοιχτών Τεχνολογιών – 5ο ΓΕΛ Βύρωνα",
    url: "https://edu.ellak.gr/2016/01/20/scholiko-ergastirio-anichton-technologion-5o-gel-virona/" }
- { desc: "Ενσωμάτωση δημιουργίας scratch σε δικτυακούς τόπους WordPress απο το ΠΣΔ",
    url: "https://edu.ellak.gr/2016/01/07/ensomatosi-dimiourgias-scratch-se-diktiakous-topous-wordpress-apo-to-psd/" }
- { desc: "Κάλεσμα: Εθελοντές Εκπαιδευτές για εισαγωγικά μαθήματα Προγραμματισμού – #gredu",
    url: "https://edu.ellak.gr/2016/01/04/kalesma-ethelontes-ekpedeftes-gia-isagogika-mathimata-programmatismou-gredu/" }

openstandards: []

openhardware: []

openwifi: []

legal: []

smartcities:
- { desc: "Ξεκίνησε το πρόγραμμα ISA² για λύσεις διαλειτουργικότητας",
    url: "https://smartcities.ellak.gr/2016/01/05/xekinise-to-programma-isa2-gia-lisis-dialitourgikotitas/" }

advisory:
- { desc: "Διαβούλευση για τον Οδηγό μετάβασης σε ανοιχτό λογισμικό ή λογισμικό ανοιχτού κώδικα (ΕΛ/ΛΑΚ) από κάθε ιδιωτικό ή δημόσιο Φορέα.",
    url: "https://advisory.ellak.gr/2016/01/29/diavoulefsi-metavasis/" }
- { desc: "Διαβούλευση για την μελέτη καταγραφής, αξιολόγησης και παρουσίασης ώριμων έργων λογισμικού και καλών πρακτικών ΕΕΛ/ΛΑΚ",
    url: "https://advisory.ellak.gr/2016/01/29/diavoulefsi-mature/" }
- { desc: "Διαβούλευση για την μελέτη για διαχείριση και απόθεση λογισμικού, δεδομένων, περιεχομένου και μελετών για τους δημόσιους φορείς και οργανισμούς",
    url: "https://advisory.ellak.gr/2016/01/29/diavoulefsi-toolkits/" }

mathe: []

wg_opengov:
- { desc: "Τα Ανοιχτά δεδομένα και η «χρηματοδότηση από το πλήθος» (crowdfunding) μπορεί να δώσουν νέα πνοή στη δημοκρατία",
    url: "https://opengov.ellak.gr/2016/01/14/ta-anichta-dedomena-ke-i-chrimatodotisi-apo-to-plithos-crowdfunding-mpori-na-dosi-nea-pnoi-sti-dimokratia/" }
- { desc: "Ανοιχτή Ηλεκτρονική Διακυβέρνηση στην Περιφέρεια Δυτικής Μακεδονίας",
    url: "https://opengov.ellak.gr/2016/01/07/anichti-ilektroniki-diakivernisi-stin-periferia-ditikis-makedonias/" }
- { desc: "Ο Δήμος Νέας Σμύρνης εγκαινίασε την λειτουργία πλατφόρμας συμμετοχής και διαλόγου",
    url: "https://opengov.ellak.gr/2016/01/06/o-dimos-neas-smirnis-egkeniase-tin-litourgia-platformas-simmetochis-ke-dialogou/" }
- { desc: "Ο πρώτος Γαλλικός ψηφιακός νόμος που συνδημιουργήθηκε από τους πολίτες",
    url: "https://opengov.ellak.gr/2016/01/05/o-protos-gallikos-psifiakos-nomos-pou-sindimiourgithike-apo-tous-polites/" }
- { desc: "Το @Avaaz είναι το παγκόσμιο κίνημα που φέρνει την φωνή των πολιτών στο επίκεντρο των πολιτικών αποφάσεων",
    url: "https://opengov.ellak.gr/2016/01/04/to-avaaz-ine-to-pagkosmio-kinima-pou-ferni-tin-foni-ton-politon-sto-epikentro-ton-politikon-apofaseon/" }

wg_opendata:
- { desc: "Οι πολλαπλές έννοιες των Ανοικτών Δημόσιων Δεδομένων (Open Government Data -OGD)",
     url: "https://opendata.ellak.gr/2016/01/04/i-pollaples-ennies-ton-anikton-dimosion-dedomenon-open-government-data-ogd/" }
 
wg_openstandards:
- { desc: "Μεταρρύθμιση των πνευματικών δικαιωμάτων στην ΕΕ: Αξιολόγηση και κάλεσμα για δράση από την Julia Reda",
    url: "https://openstandards.ellak.gr/2016/01/26/metarrithmisi-ton-pnevmatikon-dikeomaton-stin-ee-axiologisi-ke-kalesma-gia-drasi-apo-tin-julia-reda/" }

wg_openhardware:
- { desc: "Έξυπνοι Κάδοι απορριμμάτων: Ένα έργο ανοικτής σχεδίασης για το δημόσιο χώρο",
    url: "https://openhardware.ellak.gr/2016/01/27/exipni-kadi-aporrimmaton-ena-ergo-aniktis-schediasis-gia-to-dimosio-choro/" }
- { desc: "Κάδοι-μπασκέτες για διαμόρφωση οικολογικής παιδείας : Ένα έργο ανοικτής σχεδίασης για το δημόσιο χώρο",
    url: "https://openhardware.ellak.gr/2016/01/20/kadi-mpasketes-gia-diamorfosi-ikologikis-pedias-ena-ergo-aniktis-schediasis-gia-to-dimosio-choro/" }
- { desc: "pagkaki-project: Ένα έργο ανοικτής σχεδίασης για τον εξοπλισμό του δημόσιου χώρου",
    url: "https://openhardware.ellak.gr/2016/01/15/pagkaki-project-ena-ergo-aniktis-schediasis-gia-ton-exoplismo-tou-dimosiou-chorou/" }
- { desc: "DIYiotCoach: Ένα αθλητικό wearable ανοικτού hardware από τις Μονάδες Αριστείας του ΤΕΙ Αθήνας",
    url: "https://openhardware.ellak.gr/2016/01/13/diyiotcoach-ena-athlitiko-wearable-aniktou-hardware-apo-tis-monades-aristias-tou-ti-athinas/" }
- { desc: "DiyIOTCar: Αυτόνομα κινούμενο ρομποτικό αυτοκινητάκι από τις Μονάδες Αριστείας του ΤΕΙ Αθήνας",
    url: "https://openhardware.ellak.gr/2016/01/12/diyiotcar-aftonoma-kinoumeno-rompotiko-aftokinitaki-apo-tis-monades-aristias-tou-ti-athinas/" }

wg_provacy: []

wg_foss:
- { desc: "Γαλλικό κοινοβούλιο: Ο Πηγαίος κώδικας των εφαρμογών των Δημόσιων διοικήσεων θα πρέπει να είναι δημόσια διαθέσιμος",
    url: "https://opensource.ellak.gr/2016/01/14/galliko-kinovoulio-o-pigeos-kodikas-ton-efarmogon-ton-dimosion-diikiseon-tha-prepi-na-ine-dimosia-diathesimos/" }
- { desc: "Αutojudge: Σύστημα Αυτόματης Αξιολόγησης για την πλατφόρμα Openeclass από την Μονάδα Αριστείας του ΤΕΙ Αθήνας",
    url: "https://opensource.ellak.gr/2016/01/07/autojudge-sistima-aftomatis-axiologisis-gia-tin-platforma-openeclass-apo-tin-monada-aristias-tou-ti-athinas/" }
- { desc: "Ανάπτυξη νέων λειτουργιών για το edX από την Μονάδα Αριστείας του TEI Αθήνας",
    url: "https://opensource.ellak.gr/2016/01/05/anaptixi-neon-litourgion-gia-to-edx-apo-tin-monada-aristias-tou-tei-athinas/" }



wg_oer:
- { desc: "Υπολογιστική Φυσική: Ανοιχτή γνώση, ελεύθερο λογισμικό. Ένα βιβλίο με άδεια CC/GPL",
    url: "https://oer.ellak.gr/2016/01/25/ipologistiki-fisiki-anichti-gnosi-elefthero-logismiko-ena-vivlio-me-adia-ccgpl/" }

events:
- { desc: "1η εβδομάδα", url: "https://ellak.gr/2016/01/ekdilosis-tis-evdomadas-gia-tis-anichtes-technologies-ke-tin-kenotomia-69/" }
- { desc: "2η εβδομάδα", url: "https://ellak.gr/2016/01/ekdilosis-tis-evdomadas-gia-tis-anichtes-technologies-ke-tin-kenotomia-70/" }
- { desc: "3η εβδομάδα", url: "https://ellak.gr/2016/01/ekdilosis-tis-evdomadas-gia-tis-anichtes-technologies-ke-tin-kenotomia-71/" }
- { desc: "4η εβδομάδα", url: "https://ellak.gr/2016/01/ekdilosis-tis-evdomadas-gia-tis-anichtes-technologies-ke-tin-kenotomia-72/" }

main:
- { title: "Κάλεσμα της ΕΕΛ/ΛΑΚ για συντάκτες σε θέματα ανοιχτών τεχνολογιών",
    desc: "Αν έχετε ελεύθερο χρόνο, ενδιαφέρεστε για τα κοινά, το ανοιχτό λογισμικό, τις ανοιχτές τεχνολογίες, τα ανοιχτά δεδομένα, και θέλετε να  συμβάλλετε στην ανάπτυξη, προώθηση και διάδοση τους, σας καλούμε να συμμετέχετε ενεργά στην συγγραφή ή μετάφραση άρθρων στους ιστότοπους του ellak.gr για τα θέματα που σας ενδιαφέρουν.

H ΕΕΛ/ΛΑΚ με αυτή την πρόσκληση, καλεί όσους ενδιαφέρονται, να παρουσιάσουν δημόσια δράσεις για τα κοινά και την ανοιχτότητα, να συμβάλλουν στην ανάπτυξη του εθελοντισμού, να δώσουν νέες ερμηνείες και να επωφεληθούν, τόσο οι ίδιοι όσο και οι αναγνώστες των δικτυακών τόπων της ΕΕΛ/ΛΑΚ, από την δημοσίευση νέων προσεγγίσεων και ιδεών.",
    url: "https://ellak.gr/2016/01/kalesma-tis-eellak-gia-sintaktes-se-themata-anichton-technologion/",
    img: "https://ellak.gr/wp-content/uploads/2016/02/lamps.jpeg" }

- { title: "Πρόσκληση για διαβούλευση στη διαμόρφωση τριών μελετών-οδηγών για τη χρήση, διάθεση και προώθηση του ΕΛ/ΛΑΚ",
    desc: "H ΕΕΛ/ΛΑΚ καλεί όσους ενδιαφέρονται, να συμμετέχουν με σχόλια – προτάσεις στη διαμόρφωση τριών μελετών-οδηγών για τη χρήση, διάθεση και προώθηση του Ελεύθερου Λογισμικού – Λογισμικού Ανοικτού Κώδικα και των ανοικτών δεδομένων και περιεχομένου στον ευρύτερο Δημόσιο και Ιδιωτικό Τομέα στην Ελλάδα.
1) Διαβούλευση για τον Οδηγό μετάβασης σε ανοιχτό λογισμικό ή λογισμικό ανοιχτού κώδικα (ΕΛ/ΛΑΚ) από κάθε ιδιωτικό ή δημόσιο Φορέα.
2) Διαβούλευση για την μελέτη καταγραφής, αξιολόγησης και παρουσίασης ώριμων έργων λογισμικού και καλών πρακτικών ΕΕΛ/ΛΑΚ
3) Διαβούλευση για την μελέτη για διαχείριση και απόθεση λογισμικού, δεδομένων, περιεχομένου και μελετών για τους δημόσιους φορείς και οργανισμούς",
    url: "https://ellak.gr/2016/01/prosklisi-gia-diavoulefsi-sti-diamorfosi-trion-meleton-odigon-gia-ti-chrisi-diathesi-ke-proothisi-tou-ellak/",
    img: "https://ellak.gr/wp-content/uploads/2016/01/Public-Consultation-Pocess1.jpg" }

- { title: "Κάλεσμα: Εθελοντές Εκπαιδευτές για εισαγωγικά μαθήματα Προγραμματισμού – #gredu",
    desc: "Αν έχεις τον χρόνο και τις ικανότητες, τότε μπορείς να δηλώσεις εθελοντής/εκπαιδευτής στα Ανοιχτά Σχολεία που λειτουργούν στην Αθήνα, με την αιγίδα του Δήμου Αθηναίων και στο πλαίσιο της πρωτοβουλία “Σχολεία ανοιχτά στην γειτονιά, ανοιχτά στην κοινωνία” της Αντιδημαρχίας για το Παιδί, και θα απευθύνονται δωρεάν σε όλους.
Το κάλεσμα της Εταιρείας Ελεύθερου Λογισμικού/Λογισμικού Ανοιχτού Κώδικα και του Δικτύου Ενεργών Πολιτών Αθήνα απευθύνεται σε όλους όσοι ενδιαφέρονται αλλά και έχουν την δυνατότητα και προηγούμενη εμπειρία να διδάξουν στα ανοιχτά σχολεία 3 δίωρα μαθήματα εισαγωγής και εξοικείωσης με τον προγραμματισμό υπολογιστών μέσα από ανοιχτές πλατφόρμες που θα περιλαμβάνει τις παρακάτω θεματικές ενότητες",
    url: "https://edu.ellak.gr/2016/01/04/kalesma-ethelontes-ekpedeftes-gia-isagogika-mathimata-programmatismou-gredu/",
    img: "https://edu.ellak.gr/wp-content/uploads/sites/11/2016/01/open_edu_gr2.png" }

- { title: "Σχολικό Εργαστήριο Ανοιχτών Τεχνολογιών – 5ο ΓΕΛ Βύρωνα",
    desc: "Στα P9ελληνικά δημόσια σχολεία γίνονται συχνά σοβαρές προσπάθειες για την γνωριμία των μαθητών με το ΕΛ/ΛΑΚ. Υπάρχουν πολλοί εκπαιδευτικοί που επιχειρούν να μυήσουν τους μαθητές τους στον κόσμο του ανοιχτού κώδικα και μέσα από αυτόν να καλλιεργήσουν την δημιουργικότητα και την εφευρετικότητα των παιδιών.
Ένα τέτοιο σχολείο είναι το 5ο ΓΕΛ Βύρωνα, στο οποίο έχει οργανωθεί και λειτουργεί σε εβδομαδιαία βάση ένα σχολικό hackerspace. Τα παιδιά αυτά συμμετείχαν στην 8η FOSSCOΜΜ στο ΤΕΙ Αθήνας στις 7/11/2015, παρουσιάζοντας κάποιες από τις κατασκευές τους και παρακολουθώντας ομιλίες και εργαστήρια του συνεδρίου.
Αυτή ήταν η αρχή της γνωριμίας και συνεργασίας της ΕΕΛ/ΛΑΚ με το Σχολείο τους.",
    url: "https://edu.ellak.gr/2016/01/20/scholiko-ergastirio-anichton-technologion-5o-gel-virona/",
    img: "https://edu.ellak.gr/wp-content/uploads/sites/11/2016/01/Erg4i.jpg" }

- { title: "FOSDEM 2016: Η Ευρωπαϊκή γιορτή του ελεύθερου λογισμικού στις 30-31 Ιανουαρίου",
    desc: "Κάθε Ιανουάριο, περισσότεροι από 5.000 συντελεστές του ελεύθερου λογισμικού ανοικτού κώδικα από όλο τον κόσμο συρρέουν στην πανεπιστημιούπολη των Βρυξελλών, στο Βέλγιο, για ένα Σαββατοκύριακο ομιλιών, συζητήσεων και ανοικτού κώδικα. Η FOSDEM σημαίνει Free and Open Source Developers’ European Meeting,  και είναι μια από τις μεγαλύτερες εκδηλώσεις της κοινότητας που διοργανώνονται στην Ευρώπη.
Εάν είστε νέοι στον κόσμο του ανοιχτού λογισμικού, το συνέδριο αυτό είναι ένα εξαιρετικό μέρος για να μάθετε και να γνωρίσετε ανθρώπους από την κοινότητα που θα είναι περισσότερο από ευτυχείς να σας βοηθήσουν να εμπλακείτε. (Και φυσικά, θα έχετε την ευκαιρία να δοκιμάσετε την περίφημη βελγική μπύρα!).",
    url: "https://ellak.gr/2016/01/fosdem-2016-evropaiki-giorti-tou-eleftherou-logismikou-stis-30-31-ianouariou/",
    img: "https://ellak.gr/wp-content/uploads/2016/01/main.jpeg" }

- { title: "Ανοιχτή Ηλεκτρονική Διακυβέρνηση στην Περιφέρεια Δυτικής Μακεδονίας",
    desc: "Η κεντρική ιδέα που διαπερνάει οριζόντια το στρατηγικό σχεδιασμό είναι ότι η ανοικτή ηλεκτρονική διακυβέρνηση αποτελεί μια ευκαιρία για την προώθηση και υλοποίηση ριζικών μεταρρυθμίσεων. Μεταρρυθμίσεων που μπορούν να αλλάξουν θεμελιακά τη λειτουργία της περιφέρειας Δυτικής Μακεδονίας καθώς και την εικόνα της, ως οργανισμού, στα μάτια των εργαζομένων της αλλά και στις αντιλήψεις όσων διαμένουν, επιχειρούν, την επισκέπτονται ή με οποιονδήποτε τρόπο συναλλάσσονται μαζί της.",
    url: "https://opengov.ellak.gr/2016/01/07/anichti-ilektroniki-diakivernisi-stin-periferia-ditikis-makedonias/",
    img: "https://opengov.ellak.gr/wp-content/uploads/sites/10/2015/09/e-government.jpg" }

- { title: "Νικητές του ελληνικού μέρους του Διαγωνισμού Επιστημονικής Φωτογραφίας Wikimedia 2015",
    desc: "Η κριτική επιτροπή του ελληνικού μέρους του Ευρωπαϊκού Διαγωνισμού Επιστημονικής Φωτογραφίας Wikimedia έχει ολοκληρώσει την αξιολόγηση των εικόνων μέσα από δυο γύρους βαθμολόγησης, και έχει ανακοινώσει τις 10 νικήτριες εικόνες σύμφωνα με την βαθμολογία τους. Επίσης ένας μικρός αριθμός που δεν είναι στην δεκάδα αλλά είναι πρώτες στην κατηγορία τους, προωθούνται στις σχετικές κατηγορίες του Ευρωπαϊκού διαγωνισμού.
Οι πρώτες τρεις, στις οποίες απονέμονται και χρηματικά έπαθλα, είναι οι ακόλουθες:",
    url: "https://mycontent.ellak.gr/2016/01/27/nikites-tou-ellinikou-merous-tou-diagonismou-epistimonikis-fotografias-wikimedia-2015/",
    img: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Empusa_pennata_redpit.jpg" }

- { title: "Ο σκοταδισμός της πνευματικής ιδιοκτησίας – #opensource #digitalrights #greek",
    desc: "Εδώ και πολλά χρόνια οι εταιρίες παραγωγής οπτικοακουστικού υλικού και οι οργανισμοί συλλογικής διαχείρισης πνευματικών δικαιωμάτων προσπαθούν να αντιμετωπίσουν τη διακίνηση πνευματικού έργου μέσω του internet. Δεν προσπάθησαν ούτε να το κατανοήσουν, ούτε να προσαρμοστούν. Αυτό που ξεκίνησε ως προσπάθεια περιορισμού, συνεχίστηκε ως προσπάθεια καταστολής και προσπάθεια άρσης βασικών ατομικών ελευθεριών. Και δυστυχώς δεν είναι πάντα απλώς προσπάθειες. Υπάρχουν και ήττες και νίκες σ’ αυτό τον «πόλεμο».",
    url: "https://creativecommons.ellak.gr/2016/01/18/o-skotadismos-tis-pnevmatikis-idioktisias-opensource-digitalrights-greek/",
    img: "https://creativecommons.ellak.gr/wp-content/uploads/sites/19/2016/01/Digital-Rights.jpg" }

- { title: "Ξεκίνησε το πρόγραμμα ISA² για λύσεις διαλειτουργικότητας",
    desc: "Εγκρίθηκε επίσημα στις 25 Νοεμβρίου 2015 από το Ευρωπαϊκό Κοινοβούλιο και το Συμβούλιο της Ευρωπαϊκής Ένωσης, το πρόγραμμα ISA² , το οποίο ξεκινάει τον Ιανουάριο του 2016 και ολοκληρώνεται στις 31 Δεκεμβρίου 2020 ως συνέχεια του ISA.Το πρόγραμμα ISA, το οποίο διήρκεσε από το 2010 μέχρι 2015, προοριζόταν για τον εκσυγχρονισμό του δημόσιου τομέα της ΕΕ. Η πρόταση αυτή θέσπισε ένα πρόγραμμα σχετικά με λύσεις διαλειτουργικότητας για τις ευρωπαϊκές δημόσιες διοικήσεις.",
    url: "https://smartcities.ellak.gr/2016/01/05/xekinise-to-programma-isa2-gia-lisis-dialitourgikotitas/",
    img: "https://smartcities.ellak.gr/wp-content/uploads/sites/3/2016/01/isa2.jpg" }

- { title: "Οι δράσεις και η ομάδα του ODI Αthens",
    desc: "Το Open Data Institute (ODI, http://theodi.org/) ιδρύθηκε από τον εφευρέτη του Web, Sir Tim Berners-Lee και τον Sir Nigel Shadbolt με στόχο να προάγει την κουλτούρα των ανοιχτών δεδομένων στην κοινωνία, στην οικονομία και στην εκπαίδευση. Τα δύο χρόνια λειτουργίας του έχει ήδη αναπτύξει ένα σύνολο από πρωτοποριακές δράσεις οι οποίες το αναδεικνύουν σαν το σημαντικότερο διεθνές κέντρο για τα ανοιχτά δεδομένα.
Η πρωτοβουλία της ΕΕΛ/ΛΑΚ για την σύναψη συνεργασίας με το ODI και την δημιουργία του ODI Athens (http://theodi.org/nodes/odi-athens) αποσκοπεί στο να αξιοποιήσει την μοναδική τεχνογνωσία και το διεθνές δίκτυό του προς όφελος της ελληνικής κοινότητας ανοιχτών δεδομένων.",
    url: "https://ellak.gr/2016/01/drasis-ke-omada-tou-odi-athens/",
    img: "https://ellak.gr/wp-content/uploads/2016/01/logo-odi.png" }
