---

month: "Ιούλιος 2015"
title: "ΕΛΛΑΚ ΝΕΑ - {{ month }}"

ellak:
  - { desc: "Κάλεσμα εθελοντών για τεχνική υποστήριξη Ubuntu Installfests",
      url: "https://ellak.gr/2015/07/kalesma-ethelonton-gia-ipostirixi-ubuntu-installfests/" }
  - { desc: "Ευρωπαϊκή Εβδομάδα Προγραμματισμού 10-18 Οκτωβρίου 2015 – Κάνοντας τις ιδέες πράξη χάρη στον προγραμματισμό",
      url: "https://ellak.gr/2015/07/evropaiki-evdomada-programmatismou-10-18-oktovriou-2015-kanontas-tis-idees-praxi-chari-ston-programmatismo/" }
  - { desc: "Θέλετε να εγκαταστήσετε Linux στον υπολογιστή σας; Ελάτε στο Ubuntu Linux Installfest 10 Iουλίου 2015 @ INNOVATHENS, 6-9μμ",
      url: "https://ellak.gr/2015/07/ubuntu-installfest-10072015-sto-innovathens-sto-gkazi/" }
  - { desc: "Ανάπτυξη εφαρμογών κινητών τηλεφώνων – Πρόσκληση εκδήλωσης ενδιαφέροντος",
      url: "https://ellak.gr/2015/07/anaptixi-efarmogon-kiniton-tilefonon-prosklisi-ekdilosis-endiaferontos/" }
  - { desc: "Μαραθώνιος Προγραμματισμού: CROWDHACKATHON | INNOVATING WITH OPENDATA #transport",
      url: "https://ellak.gr/2015/07/marathonios-programmatismou-crowdhackathon-innovating-with-opendata-transport/" }
  - { desc: "Γίνε εκπαιδευτής στα ανοιχτά δεδομένα!",
      url: "https://ellak.gr/2015/07/gine-ekpedeftis-sta-anichta-dedomena/" }
  - { desc: "Το FI-WARE ως εργαλείο χρηματοδότησης: αξιοποιώντας ανοικτές τεχνολογίες για νεοφυείς επιχειρήσεις",
      url: "https://ellak.gr/2015/07/to-fi-ware-os-ergalio-chrimatodotisis-axiopiontas-aniktes-technologies-gia-neofiis-epichirisis/" }
  - { desc: "Ψηφιακή υπογραφή εγγράφων με τη χρήση της Ακαδημαϊκής Ταυτότητας και Ανοιχτού Λογισμικού",
      url: "https://ellak.gr/2015/07/psifiaki-ipografi-engrafon-me-ti-chrisi-tis-akadimaikis-taftotitas-ke-anichtou-logismikou/" }
  - { desc: "Τράπεζες χρόνου, εθελοντισμός και ανοικτό λογισμικό",
      url: "https://ellak.gr/2015/07/trapezes-chronou-ethelontismos-ke-anikto-logismiko/" }

cc:
  - { desc: " The List: μια εφαρμογή για κινητά από το Creative Commons",
      url: "http://creativecommons.gr/2015/07/02/the-list-%CE%BC%CE%B9%CE%B1-%CE%B5%CF%86%CE%B1%CF%81%CE%BC%CE%BF%CE%B3%CE%AE-%CE%B3%CE%B9%CE%B1-%CE%BA%CE%B9%CE%BD%CE%B7%CF%84%CE%AC-%CE%B1%CF%80%CF%8C-%CF%84%CE%BF-creative-commons/" }
  - { desc: Το Creativecommons.org διοργανώνει την πρώτη του καμπάνια στο Kickstarter! Ένα βιβλίο για ανοικτές επιχειρήσεις",
      url: "http://creativecommons.gr/2015/07/28/%CF%84%CE%BF-creativecommons-org-%CE%B4%CE%B9%CE%BF%CF%81%CE%B3%CE%B1%CE%BD%CF%8E%CE%BD%CE%B5%CE%B9-%CF%84%CE%B7%CE%BD-%CF%80%CF%81%CF%8E%CF%84%CE%B7-%CF%84%CE%BF%CF%85-%CE%BA%CE%B1%CE%BC%CF%80%CE%AC/" }
  - { desc: ALPHA – A TRANSMEDIA CINEMATIC PERFORMANCE",
      url: "http://creativecommons.gr/2015/07/31/alpha-a-transmedia-cinematic-performance-2/" }

mycontent:
  - { desc: "Ελευθερία πανοράματος: Οι εικόνες των μοντέρνων κτιρίων πρέπει να παραμείνουν στη Wikipedia",
      url: "https://mycontent.ellak.gr/2015/07/02/%CE%B5%CE%BB%CE%B5%CF%85%CE%B8%CE%B5%CF%81%CE%AF%CE%B1-%CF%80%CE%B1%CE%BD%CE%BF%CF%81%CE%AC%CE%BC%CE%B1%CF%84%CE%BF%CF%82-%CE%BF%CE%B9-%CE%B5%CE%B9%CE%BA%CF%8C%CE%BD%CE%B5%CF%82-%CF%84%CF%89%CE%BD/" }
  - { desc: "Το Μουσείο σύγχρονης τέχνης (MoMA) διαθέτει τα μεταδεδομένα της συλλογής του με άδεια CC",
      url: "https://mycontent.ellak.gr/2015/07/30/to-mousio-sigchronis-technis-moma-diatheti-ta-metadedomena-tis-sillogis-tou-me-adia-cc/" }
  - { desc: "Φωτόδεντρο: Ανοικτό ψηφιακό εκπαιδευτικό περιεχόμενο με την άδεια Creative Commons και Wikipedia",
      url: "https://mycontent.ellak.gr/2015/07/31/fotodentro-anikto-psifiako-ekpedeftiko-periechomeno-me-tin-adia-creative-commons-ke-wikipedia/" }

planet:
  - { desc: "Ubuntu Hour στο Θησείο",
      url: "https://ellak.gr/2015/07/nea-apo-ton-planiti-planet-ellak-gr-ubuntu-hour-sto-thisio/" }
  - { desc: " DrupalCon Barcelona 21-25 Σεπτεμβρίου 2015",
      url: "https://ellak.gr/2015/07/nea-apo-ton-planiti-planet-ellak-gr-drupalcon-barcelona-21-25-septemvriou-2015/" }
  - { desc: "Αναζήτηση Αναφορά από Wikimania 2015",
      url: "https://ellak.gr/2015/07/nea-apo-ton-planiti-planet-ellak-gr-anazitisi-anafora-apo-wikimania-2015/" }

opengov:
  - { desc: "Η αρχή της ουδετερότητας του διαδικτύου",
      url: "https://opengov.ellak.gr/2015/07/06/i-archi-tis-oudeterotitas-tou-diadiktiou/" }
  - { desc: "Το ζήτημα των ιδιωτικοποιήσεων και το διακύβευμα των κοινών αγαθών",
      url: "https://opengov.ellak.gr/2015/07/03/to-zitima-ton-idiotikopiiseon-ke-to-diakivevma-ton-kinon-agathon/" }

opendata:
  - { desc: "Crowdhackathon #transport: Η μεγαλύτερη ελληνική δράση κοινωνικής και επιχειρηματικής καινοτομίας ολοκληρώθηκε με επιτυχία!",
      url: "https://opendata.ellak.gr/2015/07/23/crowdhackathon-transport-i-megaliteri-elliniki-drasi-kinonikis-ke-epichirimatikis-kenotomias-oloklirothike-me-epitichia/" }

odi:
  - { desc: "Προσθεσε αξία στην δουλειά σου μέσα από τα ανοιχτα δεδομένα",
      url: "https://odi.ellak.gr/2015/07/27/prosthese-axia-stin-doulia-sou-mesa-apo-ta-anichta-dedomena/" }
  - { desc: "Πρώτη ενημέρωση για τις δράσεις του ODI Athens",
      url: "https://odi.ellak.gr/2015/07/31/proti-enimerosi-gia-tis-drasis-tou-odi-athens/" }

obs: []

edu:
  - { desc: "Σεμινάρια στις Τεχνολογίες της Πληροφορικής στην Εκπαίδευση από το ΚΕ.ΠΛΗ.ΝΕ.Τ. Κυκλάδων, 2014-2015",
      url: "https://edu.ellak.gr/2015/07/01/%CF%83%CE%B5%CE%BC%CE%B9%CE%BD%CE%AC%CF%81%CE%B9%CE%B1-%CF%83%CF%84%CE%B9%CF%82-%CF%84%CE%B5%CF%87%CE%BD%CE%BF%CE%BB%CE%BF%CE%B3%CE%AF%CE%B5%CF%82-%CF%84%CE%B7%CF%82-%CF%80%CE%BB%CE%B7%CF%81%CE%BF/" }

openhardware:
  - { desc: "Dronecode: Το ανοικτό λογισμικό και οι ανοικτές τεχνολογίες οδηγούν για άλλη μια φορά τις τεχνολογικές εξελίξεις",
      url: "https://openhardware.ellak.gr/2015/07/29/dronecode-to-anikto-logismiko-ke-i-aniktes-technologies-odigoun-gia-alli-mia-fora-tis-technologikes-exelixis/" }

openwifi: []

legal: []


openstandards:
  - { desc: "Καμπάνια του Free Software foundation για την χρήση ελεύθερης JavaScript",
      url: "https://openstandards.ellak.gr/2015/07/31/kampania-tou-free-software-foundation-gia-tin-chrisi-eleftheris-javascript/" }

events:
  - { desc: "1η εβδομάδα", url: "https://ellak.gr/2015/07/ekdilosis-tis-evdomadas-gia-tis-anichtes-technologies-ke-tin-kenotomia-45/" }
  - { desc: "2η εβδομάδα", url: "https://ellak.gr/2015/07/ekdilosis-tis-evdomadas-gia-tis-anichtes-technologies-ke-tin-kenotomia-46/" }
  - { desc: "3η εβδομάδα", url: "https://ellak.gr/2015/07/ekdilosis-tis-evdomadas-gia-tis-anichtes-technologies-ke-tin-kenotomia-47/" }
  - { desc: "4η εβδομάδα", url: "https://ellak.gr/2015/07/ekdilosis-tis-evdomadas-gia-tis-anichtes-technologies-ke-tin-kenotomia-48/" }

main:
  - { title: "Κάλεσμα για συνδιοργάνωση Ubuntu installfests σε όλη την Ελλάδα",
      desc: "Τα installfests συμβάλλουν στην έμπρακτη διάδοση και προώθηση του Ελεύθερου και Ανοικτού Λογισμικού, για να εξαπλωθεί το ανοιχτό λογισμικό σε όλες της πόλεις της Ελλάδας, καλούμε φορείς και άτομα να εκδηλώσουν ενδιαφέρον για την συνδιοργάνωση Ubuntu installfests στην πόλη τους σε συνεργασία με μέλη της EΕΛ/ΛΑΚ και τοπικές κοινότητες ανοιχτού λογισμικού.",
      url: "https://ellak.gr/2015/07/kalesma-simmetochis-gia-diorganosi-ubuntu-linux-installfests-se-oli-tin-ellada/",
      img: "https://ellak.gr/wp-content/uploads/2015/07/instalfest.png" }
  - { title: "Υπογράφηκε πλαίσιο συνεργασίας μεταξύ της Εταιρείας Ελεύθερου Λογισμικού / Λογισμικού Ανοιχτού Κώδικα και του «ΔΙΑΖΩΜΑΤΟΣ»",
      desc: "Σήμερα Τετάρτη 1 Ιουλίου 2015 υπογράφηκε πλαίσιο συνεργασίας ματαξύ της Εταιρείας Ελεύθερου Λογισμικού/Λογισμικού Ανοιχτού Κώδικα (ΕΕΛ/ΛΑΚ) και του Σωματείου ΔΙΑΖΩΜΑ. Εκπρόσωπος της ΕΕΛ/ΛΑΚ ήταν ο κ. Διομήδης Σπινέλλης, πρόεδρος του Διοικητικού Συμβουλίου της ΕΕΛ/ΛΑΚ και εκπρόσωπος από το ΔΙΑΖΩΜΑ, ο κ. Σταύρος Μπένος, πρόεδρος του Διοικητικού Συμβουλίου του «ΔΙΑΖΩΜΑΤΟΣ». Στόχος της συνεργασίας αυτής είναι να",
      url: "https://ellak.gr/2015/07/ipografike-plesio-sinergasias-metaxi-tis-eterias-eleftherou-logismikou-logismikou-anichtou-kodika-ke-tou-diazomatos/",
      img: "https://ellak.gr/wp-content/uploads/2015/07/1319_01.jpg" }
  - { title: "Διαγωνισμός Ανοιχτής Σχεδίασης Εξοπλισμού Δημοσίων Χώρων",
      desc: "Το ΕΠΙ.νοώ–ΕΜΠ σε συνεργασία με την μη κερδοσκοπική εταιρεία ΕΕΛ/ΛΑΚ προκηρύσσει διαγωνισμό με θέμα καινοτόμα συστήματα και αντικείμενα ανοιχτής σχεδίασης που μπορούν να παραχθούν τοπικά – “Openly Designed | Locally Produced”.",
      url: "https://ellak.gr/2015/07/diagonismos-anichtis-schediasis-exoplismou-dimosion-choron/",
      img: "https://ellak.gr/wp-content/uploads/2015/03/save_our_commons.jpg" }
  - { title: "ALPHA – A TRANSMEDIA CINEMATIC PERFORMANCE",
      desc: "Το Φεβρουάριο του 2013 ξεκίνησε η εκστρατεία crowdfunding για ένα πολύπλευρο καλλιτεχνικό έργο εμπνευσμένο από το μύθο της Αντιγόνης, το οποίο θα περιελάμβανε μια κινηματογραφική ταινία και μια ζωντανή κινηματογραφική παράσταση, μέσω μιας ανοιχτής διαδικασίας τόσο σε επίπεδο καλλιτεχνικής συμμετοχής, όσο και επικοινωνίας με το κοινό, για όλη τη διάρκεια υλοποίησής του. Το project αυτό λέγεται «Α» και από τον Ιούλιο του 2015 είναι ολοκληρωτικά διαθέσιμο στη σελίδα alpha-movie.com καθώς ως πολίτες του 21ου αιώνα, η δημιουργική μας ομάδα στηρίζει έμπρακτα την έννοια του OpenSource, του Free Culture και φυσικά των αδειών Creative Commons, στην πορεία μας προς μια διαφορετική, πιο ανθρωποκεντρική κοινωνία.",
      url: "http://creativecommons.gr/2015/07/31/alpha-a-transmedia-cinematic-performance-2/",
      img: "cc.jpg" }
  - { title: "Φωτόδεντρο: Ανοικτό ψηφιακό εκπαιδευτικό περιεχόμενο με την άδεια Creative Commons και Wikipedia",
      desc: "Το Φωτόδεντρο αποτελεί την κεντρική διαδικτυακή υπηρεσία του Υπουργείου Παιδείας και Θρησκευμάτων για τη συγκέντρωση, οργάνωση και διάθεση στην εκπαιδευτική κοινότητα ψηφιακού εκπαιδευτικού περιεχομένου για τη σχολική εκπαίδευση. Περιλαμβάνει μια σειρά από Ψηφιακά Αποθετήρια Εκπαιδευτικού Περιεχομένου τα οποία είναι ανοιχτά σε όλους, μαθητές, δασκάλους, γονείς αλλά και κάθε ενδιαφερόμενο. Στο φωτόδεντρο μπορείτε να βρείτε μαθησιακά αντικείμενα, δηλαδή αυτόνομες και επαναχρησιμοποιήσιμες μονάδες ψηφιακού υλικού που μπορούν να αξιοποιηθούν για τη διδασκαλία και τη μάθηση, όπως πειράματα, διαδραστικές προσομοιώσεις, διερευνήσεις, εικόνες, εκπαιδευτικά παιχνίδια, τρισδιάστατους χάρτες, ασκήσεις και άλλα. Περιλαμβάνει τη συλλογή με τα μαθησιακά αντικείμενα που αναπτύχθηκαν στο πλαίσιο του Ψηφιακού Σχολείου για τον εμπλουτισμό των σχολικών βιβλίων καθώς και συλλογές με επιλεγμένα αντικείμενα που έχουν αναπτυχθεί στο πλαίσιο διαφόρων δράσεων του Υπουργείου Παιδείας ή άλλων φορέων.",
      url: "https://mycontent.ellak.gr/2015/07/31/fotodentro-anikto-psifiako-ekpedeftiko-periechomeno-me-tin-adia-creative-commons-ke-wikipedia/",
      img: "https://mycontent.ellak.gr/wp-content/uploads/sites/18/2014/07/photodedto.png" }
  - { title: "Dronecode: Το ανοικτό λογισμικό και οι ανοικτές τεχνολογίες οδηγούν για άλλη μια φορά τις τεχνολογικές εξελίξεις",
      desc: "Το <a href='https://www.dronecode.org/'>Dronecode</a> είναι μια πλατφόρμα ανοικτού λογισμικού για μη επανδρωμένες ιπτάμενες μηχανές (Unmanned Aerial vehicles – UAV) και περιλαμβάνει έργα ανοικτού λογισμικού για τον έλεχο της πτήσης, σχεδιασμό αποστολών και γενικότερα όλες τις εφαρμογές που έχουν να κάνουν με την πτήση και την βελτιωμένη λειτουργικότητα των UAV. Αυτή η κοινή πλατφόρμα ανοικτού λογισμικού έχει υιοθετηθεί από τις περισσότερες εταιρίες που ασχολούνται με την τεχνολογία των UAV όπως η 3DRobotics, η Parrot, η Qualcomm, η Intel, η Yuneec, η Walkera, κτλ.",
      url: "https://openhardware.ellak.gr/2015/07/29/dronecode-to-anikto-logismiko-ke-i-aniktes-technologies-odigoun-gia-alli-mia-fora-tis-technologikes-exelixis/",
      img: "https://www.dronecode.org/sites/dronecode/files/pages/images/aero_cu_0.jpg" }