---

- name: Enforce root group
  group:
    name: 'root'
    gid: '0'
    system: True
    state: 'present'

- name: Enforce root user account
  user:
    name: 'root'
    state: 'present'
    shell: '{{ item.shell | default(users_default_shell) }}'
    group: 'root'
    home: '/root'
    uid: '0'
    groups: ''
    append: False
    system: True
  with_flattened:
    - users_root
  when: item.name is defined and item.name == 'root'

- name: Enforce root home permissions
  file:
    path: '/root'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'

