---

- name: Configure ~/.forward for users
  template:
    src: 'home/user/forward.j2'
    dest: '~/.forward'
    mode: '0644'
  become_user: '{{ item.name }}'
  with_flattened:
    - '{{ users_default }}'
    - '{{ users_admins }}'
    - '{{ users_list }}'
    - '{{ users_group_list }}'
    - '{{ users_host_list }}'
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state != 'absent')) and
         (item.createhome is undefined or item.createhome) and
         (item.forward is defined and item.forward))

- name: Remove ~/.forward from user account when disabled
  file:
    path: '~/.forward'
    state: 'absent'
  become_user: '{{ item.name }}'
  with_flattened:
    - '{{ users_default }}'
    - '{{ users_admins }}'
    - '{{ users_list }}'
    - '{{ users_group_list }}'
    - '{{ users_host_list }}'
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state != 'absent')) and
         (item.createhome is undefined or item.createhome) and
         (item.forward is defined and not item.forward))

