---

- name: Configure ~/.ssh/authorized_keys for users
  authorized_key:
    key: '{{ "\n".join(item.sshkeys) | string }}'
    state: 'present'
    user: '{{ item.name }}'
  with_flattened:
    - '{{ users_root }}'
    - '{{ users_default }}'
    - '{{ users_admins }}'
    - '{{ users_list }}'
    - '{{ users_group_list }}'
    - '{{ users_host_list }}'
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state != 'absent')) and
         (item.createhome is undefined or item.createhome) and
         (item.sshkeys is defined and item.sshkeys))

- name: Remove ~/.ssh/authorized_keys from user account if disabled
  file:
    path: '~/.ssh/authorized_keys'
    state: 'absent'
  become_user: '{{ item.name }}'
  with_flattened:
    - '{{ users_root }}'
    - '{{ users_default }}'
    - '{{ users_admins }}'
    - '{{ users_list }}'
    - '{{ users_group_list }}'
    - '{{ users_host_list }}'
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state != 'absent')) and
         (item.createhome is undefined or item.createhome) and
         (item.sshkeys is defined and not item.sshkeys))

