---

- name: Create user groups
  group:
    name: '{{ item.group | default(item.name) }}'
    system: '{{ item.systemgroup | default("no") }}'
    gid: '{{ item.gid | default(omit) }}'
    state: 'present'
  with_flattened:
    - users_default
    - users_admins
    - users_groups
    - users_list
    - users_group_list
    - users_host_list
  when: ((item.name is defined and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state != 'absent')))

- name: Manage user accounts
  user:
    name: '{{ item.name }}'
    uid: '{{ item.uid | default(omit) }}'
    group: '{{ item.group | default(item.name) }}'
    state: '{{ item.state | default("present") }}'
    comment: '{{ item.comment | default("") }}'
    password: '{{ item.password | default("*") }}'
    update_password: '{{ item.update_password | default("on_create") }}'
    system: '{{ item.systemuser | default("no") }}'
    shell: '{{ item.shell | default(users_default_shell) }}'
    home: '{{ item.home | default(users_default_home_prefix + "/" + item.name) }}'
    createhome: '{{ item.createhome | default(True) }}'
    expires: '{{ item.expires | default(omit) }}'
    remove: '{{ item.remove | default(omit) }}'
  with_flattened:
    - users_default
    - users_admins
    - users_list
    - users_group_list
    - users_host_list
  when: ((item.name is defined and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state)))

- name: Manage user default groups
  user:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    groups: '{{ users_default_groups_list | join(",") }}'
    append: '{{ users_default_groups_append) }}'
  with_flattened:
    - users_default
    - users_admins
    - users_list
    - users_group_list
    - users_host_list
  when: ((item.name is defined and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state != 'absent')) and
         (users_default_groups_list is defined and users_default_groups_list))

- name: Manage user groups
  user:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    groups: '{{ item.groups | join(",") }}'
    append: '{{ item.append | default("yes") }}'
  with_flattened:
    - users_default
    - users_admins
    - users_list
    - users_group_list
    - users_host_list
  when: ((item.name is defined and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state != 'absent')) and
         (item.groups is defined and item.groups))

- name: Remove user groups if requested
  group:
    name: '{{ item.group | default(item.name) }}'
    state: 'absent'
  with_flattened:
    - users_default
    - users_admins
    - users_groups
    - users_list
    - users_group_list
    - users_host_list
  when: ((item.name is defined and item.name != 'root') and
         (item.state is defined and item.state == 'absent'))

