---

# Should Ansible manage user accounts? Set to False to disable
users_enabled: True


# --- Lists of different accounts to create/manage ---

# This is only used for dotfiles management on 'root' account
users_root:
  - name: 'root'

# Default user created by Ansible
users_default:
  - name: '{{ (ansible_ssh_user
               if (ansible_ssh_user | d() and
                   ansible_ssh_user != "root")
               else lookup("env","USER")) }}'
    groups: [ 'admins' ]

# Administrators
users_admins: []

# Groups (normal or system)
users_groups: []

# "Global" users
users_list: []

# "Host group" users
users_group_list: []

# "Host" users
users_host_list: []


# --- An example account entry, everything except 'name' is optional
# List of all recognized values, default value listed first
#users_admins:
#  - '{{ users_username }}'
#
#users_username:
#  name: 'username'               # mandatory, default group if not defined
#  state: 'present,absent'
#  group: 'name'                  # default group
#  groups: []                     # list of groups to set
#  append: yes/no                 # add to, or set groups
#  gid: 1000
#  uid: 1000
#  shell: '/bin/sh'
#  comment: 'GECOS entry'
#  system: False/True             # create system user/group
#
#  home_owner: ''                 # change home directory owner
#  home_group: ''                 # change home directory group
#  home_mode: '0755'              # change home directory permissions
#
#  dotfiles: False/True           # download and configure dotfiles?
#  dotfiles_repo: 'repository'
#  dotfiles_command: 'make all'
#  dotfiles_creates '~/.zshrc'
#
#  # Create ~/.forward file (set to False to remove ~/.forward)
#  forward: [ 'user@domain', 'account' ]
#
#  # Add or disable ssh authorized keys (set to False to remove ~/.ssh/authorized_keys
#  sshkeys: [ 'list', 'of', 'keys', "{{ lookup('file', '/home/myuser/.ssh/id_rsa.pub') }}" ]
#
#  password: 'krypt pass'         # mkpasswd --method=SHA-512 oder cat /etc/shadow
#  update_password: 'on_create'   # always will update passwords if they differ.
#                                 # on_create will only set the password for newly created users. (added in Ansible 1.3)
#
#  # If account is removed, remove user's home directory as well
#  remove: False/True


# --- Global defaults ---

# If enabled, user groups and accounts will be considered "system" accounts by
# default (ie. local accounts vs LDAP accounts) and will be created with UID
# and GID < 1000.
users_default_system: '{{ (True
                           if (ansible_local|d() and ansible_local.ldap|d() and
                               ansible_local.ldap.enabled | bool)
                           else False) }}'

# List of default groups added to new accounts
users_default_groups_list: []

# Should default groups be added to existing groups, or replace existing
# groups?
users_default_groups_append: 'yes'

# Default state of dotfiles on all accounts managed by Ansible
# False - dotfiles are not configured by default
# True - dotfiles will be configured by default
users_default_dotfiles: False

# Default dotfile hash to use
users_default_dotfiles_key: 'drybjed'

# List of dotfile hashes
users_dotfiles:
  drybjed:
    repo: 'https://github.com/drybjed/dotfiles.git'
    command: 'make install'
    creates: '~/.zshrc'
    shell: '/bin/zsh'

