---

hostname: adminvm
fqdn: "{{ hostname }}.ellak.gr"

## Munin node
munin_node_bind_host: "{{ ansible_eth2.ipv4.address }}"
munin_node_bind_port: "4949"

munin_node_host_name: "{{ fqdn }}"

# Munin requires IPs be added as regular expressions.
munin_node_allowed_ips:
  - '^127\.0\.0\.1$'
  - '^::1$'
  - '{{ munin_master_regex_private_ip }}'

## ufw
ufw_whitelisted_ipv4_addresses:
  - {
    address: "{{ munin_master_private_ip }}",
    port: "{{ munin_node_bind_port }}",
    protocol: tcp
    }
ufw_whitelisted_ports:
  - {
    port: "{{ SSH_PORT }}",
    protocol: tcp
    }
  - {
    port: "{{ openvpn_hidden_port }}",
    protocol: tcp
    }
  - {
    port: 53,
    protocol: tcp
    }
  - {
    port: 53,
    protocol: udp
    }
ufw_whitelisted_port_to_port:
  - {
    port_dest: 67,
    port_src: 68,
    protocol: udp
    }

## OpenVPN
openvpn_client_config_dir: "{{ openvpn_etcdir }}/staticclients"
openvpn_port: "{{ openvpn_hidden_port }}"
openvpn_proto_s: "tcp"
openvpn_proto_c: "tcp"
openvpn_server: "10.0.0.0 255.255.255.0"
openvpn_max_clients: "10"
openvpn_user: "root"
openvpn_group: "root"
openvpn_client_to_client: yes
openvpn_server_options: 
  - push "route 10.19.91.0 255.255.255.0"
  - push "dhcp-option DNS 10.19.91.1"
  - push "dhcp-option DOMAIN ellak.lan"
  - client-config-dir "/etc/openvpn/staticclients"
  - sndbuf 0
  - rcvbuf 0
openvpn_client_options:
  - script-security 2
  - up /etc/openvpn/update-resolv-conf
  - down /etc/openvpn/update-resolv-conf
  - sndbuf 0
  - rcvbuf 0
openvpn_key_country: "GR"
openvpn_key_province: "not-defined"
openvpn_key_city: "Athens"
openvpn_key_org: "Ellak"
openvpn_key_email: "admin@eellak.gr"
openvpn_key_size: 2048
openvpn_use_pam: no
