---

hostname: adminvm
fqdn: "{{ hostname }}.ellak.gr"

## Munin node
munin_node_bind_host: "{{ ansible_eth2.ipv4.address }}"
munin_node_bind_port: "4949"

munin_node_host_name: "{{ fqdn }}"

# Munin requires IPs be added as regular expressions.
munin_node_allowed_ips:
  - '^127\.0\.0\.1$'
  - '^::1$'
  - '{{ munin_master_regex_private_ip }}'

## ufw
ufw_whitelisted_ipv4_addresses:
  - {
    address: "{{ munin_master_private_ip }}",
    port: "{{ munin_node_bind_port }}",
    protocol: tcp
    }
ufw_whitelisted_ports:
  - {
    port: 53,
    protocol: tcp
    }
  - {
    port: 53,
    protocol: udp
    }
  - {
    port: 443,
    protocol: tcp
    }
  - {
    port: 80,
    protocol: tcp
    }
  - {
    port: "{{ SSH_PORT }}",
    protocol: tcp
    }
ufw_whitelisted_port_to_port:
  - {
    port_dest: 67,
    port_src: 68,
    protocol: udp
    }
