---
hostname: db1
fqdn: "{{ hostname }}.ellak.gr"

mysql_databases:
  - name: ellakgr
    collation: utf8_general_ci
    encoding: utf8

mysql_users:
  - name: ellakgr
    host: localhost
    password: "{{ MYSQL_ELLAKGR_PASSWD }}"
    priv: "ellakgr.*:ALL"
  - name: ellakgr
    host: www2.ellak.lan
    password: "{{ MYSQL_ELLAKGR_PASSWD }}"
    priv: "ellakgr.*:ALL"
