---
# tasks file for mlmmj
- include_vars: public_lists.yml
  tags:
    - desc

- name: Create archivist directory
  file:
    dest: "{{ list_path }}/{{ item.name }}/archivist/"
    state: directory
    owner: mlmmj
    group: mlmmj
    mode: 0755
  with_items:
    - "{{ public_lists }}"
    - "{{ private_lists }}"

- name: Hide private lists
  file:
    path: "{{ list_path }}/{{ item.name }}/archivist/homeless"
    state: touch
    owner: mlmmj
    group: mlmmj
    mode: 0644
  with_items:
    - "{{ private_lists }}"

- name: Add short description
  template:
    src: shortdesc.j2
    dest: "{{ list_path }}/{{ item.name }}/archivist/shortdesc"
    owner: mlmmj
    group: mlmmj
    mode: 0644
  with_items:
    - "{{ public_lists }}"
    - "{{ private_lists }}"
  tags:
    - desc

- name: Add long description
  template:
    src: longdesc.j2
    dest: "{{ list_path }}/{{ item.name }}/archivist/longdesc"
    owner: mlmmj
    group: mlmmj
    mode: 0644
  with_items:
    - "{{ public_lists }}"
    - "{{ private_lists }}"
  tags:
    - desc

- name: Copy footer message
  template:
    src: footer.j2
    dest: "{{ list_path }}/{{ item.name }}/control/footer"
    owner: mlmmj
    group: mlmmj
    mode: 0644
  with_items:
    - "{{ public_lists }}"
    - "{{ private_lists }}"

- name: Copy mlmmj custom scripts
  copy:
    src: "bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - mlmmj-modspy
    - mlmmj-viewmods

- name: Copy cron files
  copy:
    src: "cron.d/{{ item }}"
    dest: "/etc/cron.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - mlmmj
  tags:
    - cron

- include: wikiel.yml
  tags:
    - wikiel

# Keep this task always last
#- name: Run mlmmj-archivist
#  shell: /usr/local/bin/mlmmj-archivist
#  sudo: yes
#  sudo_user: mlmmj
#  tags:
#    - archivist
