---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Munin node monitoring endpoint for RedHat/CentOS or Debian/Ubuntu.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: EL
    versions:
    - 6
    - 7
  categories:
    - monitoring
    - system
