---

- name: Set grnet source list in apt
  apt_repository: 
    repo: "deb http://apt.dev.grnet.gr {{ ansible_distribution_release }}/"
    state: present
#    filename: 'grnet'
    mode: 0644

- name: Get gpg key of grnet
  apt_key: 
    keyserver: keys.gnupg.net
    id: 9BF4F425D32A1B4C 
    state: present

- name: Install kamaki
  apt: name=kamaki state=latest update_cache=yes

- name: Copy kamakirc
  template:
    src: kamakirc.j2
    dest: /home/rsbkp/.kamakirc
    mode: 0600
    owner: rsbkp
    group: rsbkp
