---

- name: Set locale
  template:
    src: locale.j2
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644
  notify: ['restart console service']


- name: Set udev rules so interfaces have static names after reboots
  template:
    src: 70-persistent-net.rules.j2
    dest: /etc/udev/rules.d/70-persistent-net.rules
    owner: root
    group: root
    mode: 0644

- name: Set network canfiguration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  when: fqdn != 'adminvm.ellak.gr'

- name: Set hostname
  hostname: 
    name: "{{ hostname }}"

- name: Set hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: fqdn != 'adminvm.ellak.gr'

- name: Set sysctl
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644

- include: postfix.yml
