---

- name: Add jessie-backports repo
  apt_repository: 
    repo: "deb http://ftp.gr.debian.org/debian jessie-backports main contrib non-free"
    state: present
    mode: 0644

- name: Install letsencrypt and update apt's cache
  apt:
    name: letsencrypt
    state: latest
    update_cache: yes
    default_release: jessie-backports

- name: Install psutils
  apt:
    name: psutils
    state: latest

- name: Create cronjob for renewal
  template:
    src: cron.j2
    dest: /etc/cron.d/letsencrypt
    owner: root
    group: root
    mode: 0644

- name: Create script for renewal
  template:
    src: letsencrypt_renew.sh.j2
    dest: /usr/local/sbin/letsencrypt_renew.sh
    owner: root
    group: root
    mode: 0711

- stat:
    path: /etc/init.d/apache2
  register: service_status

- name : Stop nginx web-server for code.ellak.gr
  service: 
    name:  gitlab-runsvdir
    state: stopped
  when: fqdn == 'code.ellak.gr'

- name: Stop apache web-server
  service: 
    name: apache2 
    state: stopped
  when: service_status.stat.exists

- name : Stop nginx web-server
  service: 
    name: nginx
    state: stopped
  when: service_status.stat.exists == 0 and fqdn != 'code.ellak.gr'


- name: Run letsencrypt
  shell: letsencrypt certonly --text --agree-tos --email admin@eellak.gr --standalone --expand --keep --rsa-key-size 4096 {{ letsenc_domains }}

- name : Start nginx web-server for code.ellak.gr
  service: 
    name:  gitlab-runsvdir
    state: started
  when: fqdn == 'code.ellak.gr'

- name: Start apache web-server
  service:
    name: apache2
    state: started
  when: service_status.stat.exists

- name : Start nginx web-server
  service:
    name: nginx
    state: started
  when: service_status.stat.exists == 0 and fqdn != 'code.ellak.gr'
