---

- name : Stop nginx web-server for code.ellak.gr
  service: 
    name:  gitlab-runsvdir
    state: stopped
  when: fqdn == 'code.ellak.gr'

- name: Stop apache web-server
  service: 
    name: apache2 
    state: stopped
  when: service_status.stat.exists and fqdn != 'radiodev.ellak.gr'

- name : Stop nginx web-server
  service: 
    name: nginx
    state: stopped
  when: service_status.stat.exists == 0 and fqdn != 'code.ellak.gr' and fqdn != 'radiodev.ellak.gr'

- name: Run letsencrypt
  shell: certbot certonly --text --agree-tos --email sysadmin@eellak.gr --standalone --expand --keep --rsa-key-size 4096 {{ letsenc_domains }} -n
  when: fqdn != 'radiodev.ellak.gr'

- name : Start nginx web-server for code.ellak.gr
  service: 
    name:  gitlab-runsvdir
    state: started
  when: fqdn == 'code.ellak.gr'

- name: Start apache web-server
  service:
    name: apache2
    state: started
  when: service_status.stat.exists and fqdn != 'radiodev.ellak.gr'

- name : Start nginx web-server
  service:
    name: nginx
    state: started
  when: service_status.stat.exists == 0 and fqdn != 'code.ellak.gr' and fqdn != 'radiodev.ellak.gr'
