---
############################################
# Add a list of users to a mailing list.   #
############################################
##
## Usage example:
## For json formatted emails:
##  ansible-playbook playbooks/add_to_list.yml -e "list=lista @list.json"
##
## For yaml formatted emails:
##  ansible-playbook playbooks/add_to_list.yml -e "list=lista @list.yml"
##
## Where `lista` the name of the mailing list and `list.json` a json containing
## the emails to be added:
##
##  { "emails": ["mail@example.com", "mail2@wtf.org", "mail3@hello.dev"]
##
## whereas `list.yml` a yaml file containing the emails:
##
##  ---
##  emails:
##    - mail1@mail.com
##    - mail2@mail.com
##
## NOTE: the `emails` line inside either json or yaml is needed as it is called
##       by `with_items`.
##
## More info on using mlmmj: https://team.ellak.gr/projects/sitfn/wiki/Email-mlmmj
##
- hosts: mail1.ellak.gr
  sudo: true
  sudo_user: root
  gather_facts: false

  tasks:

  - name: Add users to list
    command: sudo -u mlmmj /usr/bin/mlmmj-sub -L /var/spool/mlmmj/ellak.gr/{{ list }} -a "{{ item }}" -sqf
    with_items: emails
