---

- hosts: backup
  become: true

  vars_files:
    - "{{ protected_storage }}/{{ hostname }}/bkup.yml"
    - "{{ protected_storage }}/groups/all.yml"

  roles:
    - backupninja
  tags:
    - clients

- hosts: pensieve.lan
  become: true

  vars_files:
    - ../vars/all_users.yml

  roles:
    - sftpusers
    - sshkeys
  tags:
    - server

#  tasks:
#    - name: Copy GPG dir to /tmp
#      shell: tar -czf /tmp/{{ hostname }}_gpg_dir.tar /root/.gnupg
# 
#    - name: Change permissions
#      shell: chown nick:nick /tmp/{{ hostname }}_gpg_dir.tar
# 
#    - name: Fetch files
#      fetch: src=/tmp/{{ hostname }}_gpg_dir.tar dest=/tmp/bkup_gpg_keys/ flat=yes
#
#    - name: Delete file
#      file:
#        path: /tmp/{{ hostname }}_gpg_dir.tar
#        state: absent
