---

- hosts: backup
  become: true

  vars_files:
    - "{{ protected_storage }}/{{ fqdn }}/bkup.yml"
    - "{{ protected_storage }}/groups/all.yml"

  roles:
    - backupninja
  tags:
    - clients

- hosts: pensieve.lan
  become: true

  vars_files:
    - ../vars/all_users.yml

  roles:
    - sftpusers
    - sshkeys
  tags:
    - server
