---

- hosts: adminvm.ellak.gr
  become: true

  vars_files:
    - "{{ protected_storage }}/adminvm.ellak.gr/openvpn.yml"
    - "{{ protected_storage }}/adminvm.ellak.gr/ufw.yml"

  vars:
    - openvpn_clients:
      - pensieve.ellak.gr
      - ma.ellak.gr
      - mail1.ellak.gr
      - nick.user

  roles:
    - openvpn-server
    - ufw

  tags:
    - server

- hosts: vpn
  become: true

  vars:
    - openvpn_dns: no

  roles:
    - openvpn-client

  tags:
    - clients
