---
# You have to provide two variables, for example:
#   -e 'fqdn=db1.ellak.gr' -e 'hostname=db1'
#
- hosts: all
  sudo: true
  sudo_user: root

  vars_files:
    - "{{ protected_storage }}/mail1.ellak.gr/private.yml"

  roles:
    - roles/postinstall
