---
# https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
- name: Reboot
  hosts: all
  become: true
  become_user: root

  tasks:

  - name: Remove molly-guard
    apt: name=molly-guard state=absent

  - name: Reboot server
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true

  - name: Waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }}
                  state=started
    become: false

  - name: Install molly-guard
    apt: name=molly-guard state=present
