---

- hosts: tomcat
  become: true

  vars_files:
    - "{{ protected_storage }}/tomcat.ellak.gr/ufw.yml"

  pre_tasks:

  roles:
    - { role: ufw, tags: ['ufw', 'firewall'] }
    - { role: munin-node, tags: ['munin-node', 'munin'] }
