---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install Memcached.
  apt: name=memcached state=installed

- name: Create memcache user
  user:
    name: "{{ memcached_user | default(__memcached_user) }}"
    #    group: "{{ memcached_user | default(__memcached_user) }}"
    shell: /sbin/nologin
