---
php_packages:
  - php5
  - php5-geoip
  - php5-imagick
  - php5-cgi
  - php5-cli
  - php5-common
  - php5-curl
  - php5-gd
  - php5-mcrypt
  - php5-mysql
  - php-apcu
  - php-mail
  - php-net-smtp
  - php-pear
