---

#################################################
# Remove a list of users from a mailing list.   #
#################################################
##
## Usage example:
## For json formatted emails:
##  ansible-playbook playbooks/rm_from_list.yml -e "list=lista" -e "@list.json"
##
## For yaml formatted emails:
##  ansible-playbook playbooks/rm_from_list.yml -e "list=lista" -e "@list.yml"
##
## Where `lista` the name of the mailing list and `list.json` a json containing
## the emails to be removed:
##
##  { "emails": ["mail@example.com", "mail2@wtf.org", "mail3@hello.dev"]
##
## whereas `list.yml` a yaml file containing the emails:
##
##  ---
##  emails:
##    - mail1@mail.com
##    - mail2@mail.com
##
## NOTE: the `emails` line inside either json or yaml is needed as it is called
##       by `with_items`.
##
## More info on using mlmmj: https://team.ellak.gr/projects/sitfn/wiki/Email-mlmmj
##
- hosts: mail1
  sudo: true
  sudo_user: root

  tasks:

  - name: Remove users from list
    command: sudo -u mlmmj /usr/bin/mlmmj-unsub -L /var/spool/mlmmj/ellak.gr/{{ list }} -a "{{ item }}" -q
    with_items: emails
